travis:
  secure:
    BINSTAR_TOKEN: itT2ct6Q7ax1k9g/maEKPXrvyOJnTwnN/b5z9ssEJ1yZesvjj52WCRfQ8qCWBRUAjLwMxICRIsM2ZV5pXFEXo2HLsRfAUmTeVVm9AK0HTg4zr/BeU6+HDmTEX1nLozqjdkLBb9FO9+zQpO8hlGIu+LHPAuSfEKbNFer9RmBIQt2h2SdO8Z8gMo8Mcgz7ahVLFama5sEi5IvZ7R9qx1yk6QueVxYRR/pHdv+NY7GNS/oluF9SRT0oFnSoAkL91Etinws1nAnbly0V/0XcF2rNpueZCceprH6/Vk1qwmXLUNGMTE508NTXN20ZunA9i1ANBrsHlm3znWQDsWYmp2C3uNITdJcEflcQHa1HBh9jLVSmxuNMxJLVoOaMgIWDz7t637D0PHXtfqudJUJhvQk5i03KTSreLBMrlcDe6mL36lMGpnJHQtcDj6Btu6WxlY6Go1fTJUhVndjEROM+T+iRA4zi8HEOZSsIVMOQv0BnB35g36YijyZSBDFOMTau02TY3Qfvokjr3IhFwyfXw8AIAfm1MaDcy2BY83IaoaSTRvVU2akhteQJmXcy5NUgId9fbpKzX2M7v7eNjCnfzFYfUksnCfHoORJ1x8nq1jqXPAEY1S0izFY04N5q9JIktYICEuTJmfD0i50jRLBU7+0Pep9VZ+2RUhNRF5ajzyQLvAY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
